# https://docs.netlify.com/configure-builds/file-based-configuration/

# The following redirect is intended for use with most SPAs 
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

  # By default, redirects won’t be applied if there’s a file 
  # with the same path as the one defined in the `from` property.
  # Setting `force` to `true` will make the redirect rule
  # take precedence over any existing files.
  # force = true

[[redirects]]
  from = "/internallink"
  to = "/index.html"
  status = 200